export const GET_MOVIE_INDEX_PENDING = 'GET_MOVIE_INDEX_PENDING';
export const GET_MOVIE_INDEX_SUCCESS = 'GET_MOVIE_INDEX_SUCCESS';
export const GET_MOVIE_BY_ID_SUCCESS = 'GET_MOVIE_BY_ID_SUCCESS';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_PENDING = 'SEARCH_PENDING';
export const ES_AUTOCOMPLETE_SUCCESS = 'ES_AUTOCOMPLETE_SUCCESS';
export const ES_SEARCH_SUCCESS = 'ES_SEARCH_SUCCESS';